-- MySQL Script generated by MySQL Workbench
-- Sun Feb  7 14:29:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`userEntity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userEntity` (
  `ID` INT NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `Confirm` TINYINT NOT NULL,
  `Active` TINYINT NOT NULL,
  `Avatar` VARCHAR(45) NOT NULL,
  `Salt` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `Password_updated_at` DATETIME NOT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`User has role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User has role` (
  `ID_USER` INT NOT NULL,
  `ID_ROLE` INT NOT NULL,
  `Created_at` DATETIME NOT NULL,
  `Updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`ID_USER`, `ID_ROLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role Entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role Entity` (
  `ID` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `Created_at` DATETIME NOT NULL,
  `Updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passwork Entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passwork Entity` (
  `ID` INT NOT NULL,
  `ID_USER` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `passphrase` VARCHAR(45) NOT NULL,
  `Description` TEXT(999) NOT NULL,
  `Url` VARCHAR(45) NOT NULL,
  `Created_at` DATETIME NOT NULL,
  `Updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`ID`, `ID_USER`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
